Repository SonicCloudOrg/sonic-client-web, pull requests merged in 2022-09, with the labels that each got.

#195 fix：translate
  src/components/TestCaseList.vue
  src/components/TestCaseUpdate.vue
  src/locales/lang/en_US.js
  src/locales/lang/ja_JP.js
  src/locales/lang/zh_CN.js
  src/locales/lang/zh_TW.js
  src/views/AndroidTestCase.vue
  src/views/Devices.vue
  src/views/Elements.vue
  src/views/GlobalParams.vue
  src/views/Home.vue
  src/views/IOSTestCase.vue
  src/views/Jobs.vue
  src/views/Login.vue
  src/views/Modules.vue
  src/views/Packages.vue
Labels: fix

#199 fix:translate
  src/locales/lang/en_US.js
  src/locales/lang/ja_JP.js
  src/locales/lang/zh_CN.js
  src/locales/lang/zh_TW.js
  src/views/Elements.vue
  src/views/GlobalParams.vue
  src/views/Home.vue
  src/views/IOSTestCase.vue
  src/views/Jobs.vue
  src/views/Login.vue
  src/views/Modules.vue
  src/views/Packages.vue
  src/views/ProjectIndex.vue
  src/views/PublicStep.vue
  src/views/RemoteEmulator/AndroidRemote.vue
  src/views/RemoteEmulator/IOSRemote.vue
  src/views/RemoteEmulator/index.vue
  src/views/RemoteEmulator/indexIOS.vue
  src/views/ResultDetail.vue
  src/views/Results.vue
  src/views/Setting/Index.vue
  src/views/Setting/Resource.vue
  src/views/Setting/Role.vue
  src/views/Setting/SysJobs.vue
  src/views/Setting/Users.vue
  src/views/StepListView.vue
  src/views/TestSuites.vue
  src/views/Versions.vue
Labels: fix

#200 feat: translate
  src/locales/lang/en_US.js
  src/locales/lang/ja_JP.js
  src/locales/lang/zh_CN.js
  src/locales/lang/zh_TW.js
  src/views/Elements.vue
  src/views/GlobalParams.vue
  src/views/Home.vue
  src/views/IOSTestCase.vue
  src/views/Jobs.vue
  src/views/Login.vue
  src/views/Modules.vue
  src/views/Packages.vue
  src/views/ProjectIndex.vue
  src/views/PublicStep.vue
  src/views/RemoteEmulator/AndroidRemote.vue
  src/views/RemoteEmulator/IOSRemote.vue
  src/views/RemoteEmulator/index.vue
  src/views/RemoteEmulator/indexIOS.vue
  src/views/ResultDetail.vue
  src/views/Results.vue
  src/views/Setting/Index.vue
  src/views/Setting/Resource.vue
  src/views/Setting/Role.vue
  src/views/Setting/SysJobs.vue
  src/views/Setting/Users.vue
  src/views/StepListView.vue
  src/views/TestSuites.vue
  src/views/Versions.vue
Labels: feature

#201 fix:修复翻译bug
  src/locales/lang/en_US.js
  src/locales/lang/ja_JP.js
  src/locales/lang/zh_CN.js
  src/locales/lang/zh_TW.js
  src/views/GlobalParams.vue
  src/views/IOSTestCase.vue
  src/views/Versions.vue
Labels: fix

#202 fix:修复翻译bug
  src/locales/lang/en_US.js
  src/locales/lang/ja_JP.js
  src/locales/lang/zh_CN.js
  src/locales/lang/zh_TW.js
  src/views/Devices.vue
  src/views/RemoteEmulator/AndroidRemote.vue
  src/views/RemoteEmulator/IOSRemote.vue
  src/views/ResultDetail.vue
Labels: fix

#203 [doc] 懇請複查繁體中文翻譯是否適當
  src/locales/lang/zh_TW.js
Labels: document

#204 [doc] Update zh_TW.js (新增95 ~ 103行翻譯)
  src/locales/lang/zh_TW.js
Labels: document
